#include "MockFileProviderPlugin.h"

#include <algorithm>
#include <atomic>
#include <optional>

#include <QBuffer>
#include <QDateTime>
#include <QIODevice>
#include <QList>
#include <QStringList>

namespace {

struct MockNode {
    QString path;
    QString name;
    bool directory = false;
    QByteArray content;
};

QString normalizedMockPath(QString path)
{
    path = path.trimmed();
    const int separatorIndex = path.indexOf(QStringLiteral("://"));
    if (separatorIndex < 0) {
        const QString lower = path.toLower();
        if (lower == QStringLiteral("mock:") || lower == QStringLiteral("mock:/")) {
            return QStringLiteral("mock://");
        }
        return {};
    }

    const QString scheme = path.left(separatorIndex).toLower();
    if (scheme != QStringLiteral("mock")) {
        return {};
    }

    QString tail = path.mid(separatorIndex + 3);
    tail.replace(QLatin1Char('\\'), QLatin1Char('/'));
    while (tail.startsWith(QLatin1Char('/'))) {
        tail.remove(0, 1);
    }
    while (tail.endsWith(QLatin1Char('/'))) {
        tail.chop(1);
    }

    if (tail.isEmpty()) {
        return QStringLiteral("mock://");
    }

    const QStringList parts = tail.split(QLatin1Char('/'), Qt::SkipEmptyParts);
    return QStringLiteral("mock://") + parts.join(QLatin1Char('/'));
}

QString parentMockPath(const QString &path)
{
    const QString normalized = normalizedMockPath(path);
    if (normalized.isEmpty() || normalized == QStringLiteral("mock://")) {
        return {};
    }

    const QString tail = normalized.mid(QStringLiteral("mock://").size());
    const int slashIndex = tail.lastIndexOf(QLatin1Char('/'));
    if (slashIndex < 0) {
        return QStringLiteral("mock://");
    }
    return QStringLiteral("mock://") + tail.left(slashIndex);
}

QString fileNameForMockPath(const QString &path)
{
    const QString normalized = normalizedMockPath(path);
    if (normalized == QStringLiteral("mock://")) {
        return QStringLiteral("Mock");
    }
    const QString tail = normalized.mid(QStringLiteral("mock://").size());
    const int slashIndex = tail.lastIndexOf(QLatin1Char('/'));
    return slashIndex < 0 ? tail : tail.mid(slashIndex + 1);
}

QString childMockPath(const QString &parentPath, const QString &name)
{
    const QString normalizedParent = normalizedMockPath(parentPath);
    const QString cleanName = QString(name).trimmed().replace(QLatin1Char('\\'), QLatin1Char('/'));
    const QStringList parts = cleanName.split(QLatin1Char('/'), Qt::SkipEmptyParts);
    if (normalizedParent.isEmpty() || parts.isEmpty()) {
        return normalizedParent;
    }
    if (normalizedParent == QStringLiteral("mock://")) {
        return normalizedParent + parts.join(QLatin1Char('/'));
    }
    return normalizedParent + QLatin1Char('/') + parts.join(QLatin1Char('/'));
}

QString suffixForName(const QString &name)
{
    const int dotIndex = name.lastIndexOf(QLatin1Char('.'));
    if (dotIndex <= 0 || dotIndex == name.size() - 1) {
        return {};
    }
    return name.mid(dotIndex + 1).toLower();
}

QString byteSizeText(qint64 size)
{
    if (size < 1024) {
        return QStringLiteral("%1 B").arg(size);
    }
    const double kib = double(size) / 1024.0;
    if (kib < 1024.0) {
        return QStringLiteral("%1 KB").arg(kib, 0, 'f', 1);
    }
    return QStringLiteral("%1 MB").arg(kib / 1024.0, 0, 'f', 1);
}

QDateTime mockModifiedTime()
{
    return QDateTime::fromString(QStringLiteral("2026-01-01T12:00:00Z"), Qt::ISODate);
}

QList<MockNode> makeNodes()
{
    const QByteArray readme =
        "mock:// provider\n"
        "\n"
        "This tree is generated by a QPluginLoader FileProvider plugin.\n"
        "It is read-only and exists only to exercise remote-provider navigation.\n";
    const QByteArray notes =
        "# Remote provider notes\n"
        "\n"
        "- scheme routing\n"
        "- provider-owned normalization\n"
        "- breadcrumbs for URI paths\n";
    const QByteArray alpha =
        "Alpha project lives entirely inside mock://.\n";
    const QByteArray longNote =
        "This file sits below an intentionally long folder name so breadcrumbs can be tested.\n";

    return {
        {QStringLiteral("mock://"), QStringLiteral("Mock"), true, {}},
        {QStringLiteral("mock://Documents"), QStringLiteral("Documents"), true, {}},
        {QStringLiteral("mock://Documents/Specs"), QStringLiteral("Specs"), true, {}},
        {QStringLiteral("mock://Documents/Specs/remote-provider-notes.md"), QStringLiteral("remote-provider-notes.md"), false, notes},
        {QStringLiteral("mock://Documents/readme.txt"), QStringLiteral("readme.txt"), false, readme},
        {QStringLiteral("mock://Media"), QStringLiteral("Media"), true, {}},
        {QStringLiteral("mock://Media/Images"), QStringLiteral("Images"), true, {}},
        {QStringLiteral("mock://Media/Images/sunrise.mock"), QStringLiteral("sunrise.mock"), false, QByteArray("Pretend image bytes\n")},
        {QStringLiteral("mock://Projects"), QStringLiteral("Projects"), true, {}},
        {QStringLiteral("mock://Projects/Alpha"), QStringLiteral("Alpha"), true, {}},
        {QStringLiteral("mock://Projects/Alpha/demo.txt"), QStringLiteral("demo.txt"), false, alpha},
        {QStringLiteral("mock://Projects/Bravo"), QStringLiteral("Bravo"), true, {}},
        {QStringLiteral("mock://Projects/Bravo/empty-folder"), QStringLiteral("empty-folder"), true, {}},
        {QStringLiteral("mock://Edge Cases"), QStringLiteral("Edge Cases"), true, {}},
        {QStringLiteral("mock://Edge Cases/Very Long Folder Name That Should Exercise Breadcrumb Middle Ellipsis Before Remote Providers Arrive"),
         QStringLiteral("Very Long Folder Name That Should Exercise Breadcrumb Middle Ellipsis Before Remote Providers Arrive"),
         true,
         {}},
        {QStringLiteral("mock://Edge Cases/Very Long Folder Name That Should Exercise Breadcrumb Middle Ellipsis Before Remote Providers Arrive/deep-note.txt"),
         QStringLiteral("deep-note.txt"),
         false,
         longNote},
    };
}

const QList<MockNode> &mockNodes()
{
    static const QList<MockNode> nodes = makeNodes();
    return nodes;
}

const MockNode *nodeForPath(const QString &path)
{
    const QString normalized = normalizedMockPath(path);
    if (normalized.isEmpty()) {
        return nullptr;
    }

    const QList<MockNode> &nodes = mockNodes();
    const auto it = std::find_if(nodes.cbegin(), nodes.cend(), [&normalized](const MockNode &node) {
        return node.path == normalized;
    });
    return it == nodes.cend() ? nullptr : &(*it);
}

QList<const MockNode *> childNodesForPath(const QString &path)
{
    QList<const MockNode *> children;
    const QString normalized = normalizedMockPath(path);
    if (normalized.isEmpty()) {
        return children;
    }

    for (const MockNode &node : mockNodes()) {
        if (node.path == normalized) {
            continue;
        }
        if (parentMockPath(node.path) == normalized) {
            children.append(&node);
        }
    }

    std::sort(children.begin(), children.end(), [](const MockNode *left, const MockNode *right) {
        if (left->directory != right->directory) {
            return left->directory && !right->directory;
        }
        return QString::compare(left->name, right->name, Qt::CaseInsensitive) < 0;
    });
    return children;
}

FileEntry entryFromNode(const MockNode &node)
{
    FileEntry entry;
    entry.name = node.name;
    entry.path = node.path;
    entry.suffix = node.directory ? QString{} : suffixForName(node.name);
    entry.size = node.directory ? 0 : node.content.size();
    entry.sizeText = node.directory ? QString{} : byteSizeText(entry.size);
    entry.modified = mockModifiedTime();
    entry.created = entry.modified;
    entry.modifiedText = entry.modified.toString(Qt::ISODate);
    entry.createdText = entry.created.toString(Qt::ISODate);
    entry.attributesText = node.directory ? QStringLiteral("Virtual folder") : QStringLiteral("Read-only");
    entry.isDirectory = node.directory;
    entry.isReadOnly = true;
    return entry;
}

class MockFileProvider final : public FileProvider
{
public:
    explicit MockFileProvider(QObject *parent = nullptr)
        : FileProvider(parent)
    {
    }

    QString scheme() const override { return QStringLiteral("mock"); }
    bool canHandle(const QString &path) const override { return !normalizedMockPath(path).isEmpty(); }
    Capabilities capabilities() const override { return Browse | ReadMetadata | Transfer; }

    void scan(const QString &path) override
    {
        m_currentPath = normalizedPath(path);
        m_running.store(true);
        const int generation = m_generation.fetch_add(1) + 1;
        emit started();

        const MockNode *node = nodeForPath(m_currentPath);
        if (!node || !node->directory) {
            m_running.store(false);
            emit finished(m_currentPath, false, generation, QStringLiteral("Mock path does not exist"));
            return;
        }

        QList<FileEntry> entries;
        const QList<const MockNode *> children = childNodesForPath(m_currentPath);
        entries.reserve(children.size());
        for (const MockNode *child : children) {
            entries.append(entryFromNode(*child));
        }

        if (!entries.isEmpty()) {
            emit batchReady(entries, generation);
        }
        m_running.store(false);
        emit finished(m_currentPath, true, generation, {});
    }

    void cancel() override
    {
        m_generation.fetch_add(1);
        m_running.store(false);
    }

    void setShowHidden(bool show) override { m_showHidden = show; }
    bool isRunning() const override { return m_running.load(); }
    QString currentPath() const override { return m_currentPath; }
    int currentGeneration() const override { return m_generation.load(); }
    bool pathExists(const QString &path) const override { return nodeForPath(path) != nullptr; }
    bool isDirectory(const QString &path) const override
    {
        const MockNode *node = nodeForPath(path);
        return node && node->directory;
    }
    bool isSymLink(const QString &) const override { return false; }
    QString normalizedPath(const QString &path) const override { return normalizedMockPath(path); }
    QString fileName(const QString &path) const override { return fileNameForMockPath(path); }
    QString absolutePath(const QString &path) const override { return normalizedMockPath(path); }
    QString parentPath(const QString &path) const override { return parentMockPath(path); }
    QString childPath(const QString &parentPath, const QString &name) const override { return childMockPath(parentPath, name); }

    std::optional<FileEntry> entryInfo(const QString &path) const override
    {
        const MockNode *node = nodeForPath(path);
        if (!node) {
            return std::nullopt;
        }
        return entryFromNode(*node);
    }

    bool ensureParentDirectory(const QString &) const override { return failReadOnly(); }
    bool makePath(const QString &) const override { return failReadOnly(); }
    bool removePath(const QString &) const override { return failReadOnly(); }

    QStringList childPaths(const QString &path, bool includeHidden = true) const override
    {
        Q_UNUSED(includeHidden)
        QStringList paths;
        const QList<const MockNode *> children = childNodesForPath(path);
        paths.reserve(children.size());
        for (const MockNode *child : children) {
            paths.append(child->path);
        }
        return paths;
    }

    bool movePath(const QString &, const QString &) const override { return failReadOnly(); }

    std::unique_ptr<QIODevice> openRead(const QString &path) const override
    {
        clearLastError();
        const MockNode *node = nodeForPath(path);
        if (!node || node->directory) {
            setLastError(QStringLiteral("Mock file does not exist"));
            return nullptr;
        }

        auto buffer = std::make_unique<QBuffer>();
        buffer->setData(node->content);
        if (!buffer->open(QIODevice::ReadOnly)) {
            setLastError(QStringLiteral("Cannot open mock buffer"));
            return nullptr;
        }
        return buffer;
    }

    std::unique_ptr<QIODevice> openWrite(const QString &, bool truncate = true) const override
    {
        Q_UNUSED(truncate)
        failReadOnly();
        return nullptr;
    }

    bool renamePath(const QString &, const QString &) override { return failReadOnly(); }
    bool createFolder(const QString &, const QString &, QString *createdPath = nullptr) override
    {
        if (createdPath) {
            createdPath->clear();
        }
        return failReadOnly();
    }
    bool createFile(const QString &, const QString &, QString *createdPath = nullptr) override
    {
        if (createdPath) {
            createdPath->clear();
        }
        return failReadOnly();
    }

    QString lastErrorString() const override { return m_lastError; }
    void clearLastError() const override { m_lastError.clear(); }

private:
    bool failReadOnly() const
    {
        setLastError(QStringLiteral("mock:// is read-only"));
        return false;
    }

    void setLastError(const QString &error) const
    {
        m_lastError = error;
    }

    QString m_currentPath = QStringLiteral("mock://");
    std::atomic<int> m_generation{0};
    std::atomic_bool m_running{false};
    bool m_showHidden = false;
    mutable QString m_lastError;
};

} // namespace

int MockFileProviderPlugin::apiVersion() const
{
    return FM_FILE_PROVIDER_PLUGIN_API_VERSION;
}

QString MockFileProviderPlugin::pluginId() const
{
    return QStringLiteral("fm.mock-provider");
}

QString MockFileProviderPlugin::displayName() const
{
    return QStringLiteral("Mock Virtual Provider");
}

QStringList MockFileProviderPlugin::schemes() const
{
    return {QStringLiteral("mock")};
}

bool MockFileProviderPlugin::canHandle(const QString &path) const
{
    return !normalizedMockPath(path).isEmpty();
}

std::unique_ptr<FileProvider> MockFileProviderPlugin::createProvider()
{
    return std::make_unique<MockFileProvider>();
}

int MockFileProviderPlugin::actionApiVersion() const
{
    return FM_FILE_ACTION_PLUGIN_API_VERSION;
}

QString MockFileProviderPlugin::actionPluginId() const
{
    return pluginId();
}

QString MockFileProviderPlugin::actionDisplayName() const
{
    return displayName();
}

QList<FileActionDescriptor> MockFileProviderPlugin::actionsForContext(const FileActionContext &context) const
{
    Q_UNUSED(context)
    return {};
}

QVariantMap MockFileProviderPlugin::triggerAction(const QString &actionId, const FileActionContext &context)
{
    if (actionId == QStringLiteral("mock.item-info")) {
        QString normalizedPath = context.targetPath;
        normalizedPath.replace(QLatin1Char('\\'), QLatin1Char('/'));
        const QString targetName = normalizedPath.section(QLatin1Char('/'), -1);
        return {
            {QStringLiteral("title"), QStringLiteral("Mock Item Action")},
            {QStringLiteral("message"),
             QStringLiteral("Item: %1\nPath: %2\nCurrent folder: %3")
                 .arg(targetName.isEmpty() ? QStringLiteral("(unknown)") : targetName,
                      context.targetPath,
                      context.currentPath)},
        };
    }

    if (actionId == QStringLiteral("mock.folder-info")) {
        return {
            {QStringLiteral("title"), QStringLiteral("Mock Folder Action")},
            {QStringLiteral("message"),
             QStringLiteral("Current folder:\n%1").arg(context.currentPath)},
        };
    }

    return {
        {QStringLiteral("title"), QStringLiteral("Mock Action")},
        {QStringLiteral("message"), QStringLiteral("Unknown mock action.")},
    };
}
